version: '3'

services:
  web:
    build: .
    depends_on:
      - cms
    environment:
      DARE_CMS_ROOT_URI: http://cms:1337/
      DARE_ASSET_ROOT_URI: http://localhost:3001/
    ports:
      - 3000:3000

  cms:
    build: cms
    depends_on:
      - mongo
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_NAME: dare
      DATABASE_USERNAME: dare
      DATABASE_PASSWORD: secret
    ports:
      - 3001:1337

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: dare
      MONGO_INITDB_ROOT_USERNAME: dare
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - ./mongodata:/data/db
